//插入mysql失败的再次插入
const mongoose = require('mongoose');
const bookModel= mongoose.model('bookList');
const {getModel} = require("../model/schema/bookItem");
const mysql = require("mysql");
const moment = require('moment');
const bagPipe = require('bagpipe');
const bag = new bagPipe(2);
const fs = require('fs');
var inow = 0;
var lodash = require('lodash');

const connition = mysql.createConnection({
    host: "192.168.1.149",
    port: 3306,
    user:'admin',
    password:'New_shidai2017',
    database: "book",
})




connition.connect(function (err) {
    if (err){
        console.log('链接失败',err)
    } else{
        console.log("链接成功");

        clData();
    }
})

async function  saveData(item){


    var key=item.key;
    var dataBase=item.dataBase;
    var chapter = item.chapter;



    console.log(key,chapter);
    var bookItem = await getModel(key).findOne({chapter:chapter});

    console.log(bookItem)
   if (!bookItem){
       console.log(item.key+'-------')
   }
          /* connition.query(
             "INSERT INTO "+ dataBase+" SET ?",{
               id:null,
               bookid:key,
               name:bookItem.name,
               chapter:bookItem.chapter,
               content:bookItem.content,
               serial:bookItem.serial

              },
           /!* connition.query("INSERT INTO "+dataBase+" SELECT ? FROM "+ dataBase+" WHERE NOT EXISTS (select * from "+dataBase+" where name=? AND chapter=?);",
            [
                {
                    id:null,
                    bookid:key,
                    name:bookItem.name,
                    chapter:bookItem.chapter,
                    content:bookItem.content,
                    serial:bookItem.serial
                }
                ,bookItem.name,chapter
            ],*!/
            function (err) {
                if (err){
                    console.log("插入失败"+key+'---'+bookItem.chapter+'-----',err);
                    fs.appendFile('./error.txt',"插入失败"+key+'----'+dataBase+'---'+bookItem.chapter+'-----'+'\n',function (err) {
                        if (err){
                            console.log('写入失败')
                        } else{
                            console.log('写入成功')
                        }
                    });
                } else {
                    console.log("插入成功"+key+'---'+bookItem.chapter+'-----');
                }
            })*/
}

async function clData() {
    var arry = [
        {key:"lt1171",dataBase:"database5",chapter:"第六十二章    八风不动，如山！"},
        {key:"lt1559",dataBase:"database5",chapter:"第191章节 染血的圣洁"},
        {key:"lt1559",dataBase:"database5",chapter:"第197章节 千鸟屋"},
        {key:"lt1559",dataBase:"database5",chapter:"第201章节 神器归属"},
        {key:"lt1559",dataBase:"database5",chapter:"第195章节 阿罗德的爱恋"},
        {key:"lt1559",dataBase:"database5",chapter:"第196章节 雪岩地下城"},
        {key:"lt1559",dataBase:"database5",chapter:"第199章节 决斗前的赌局（下）"},
        {key:"lt1559",dataBase:"database5",chapter:"第204章节 影神"},
        {key:"lt1559",dataBase:"database5",chapter:"第235章节 玛蒙"},
        {key:"lt1559",dataBase:"database5",chapter:"第258章节"},
        {key:"lt1559",dataBase:"database5",chapter:"第275章节"},
        {key:"lt152",dataBase:"database4",chapter:"第二十二章 未来之约"},
        {key:"lt132",dataBase:"database4",chapter:"第三百五十一章 头上的星空，内心的道德法则"},
        {key:"lt132",dataBase:"database4",chapter:"第三百五十章 放下"},
        {key:"lt1414",dataBase:"database1",chapter:"第360章：忆情地穴"},
        {key:"lt1414",dataBase:"database1",chapter:"第361章：王者狭情"},
        {key:"lt1414",dataBase:"database1",chapter:"第372章：向死之心"},
        {key:"lt1414",dataBase:"database1",chapter:"第376章：遗情千年"},
        {key:"lt1414",dataBase:"database1",chapter:"第374章：死亡性事（上）"},
        {key:"lt1414",dataBase:"database1",chapter:"第375章：死亡性事（下）"},
        {key:"lt1414",dataBase:"database1",chapter:"第371章：离歌新主"},
        {key:"lt1414",dataBase:"database1",chapter:"第373章：黄雀，黄雀！"},
        {key:"lt1414",dataBase:"database1",chapter:"第378章：古城陨落"},
        {key:"lt1414",dataBase:"database1",chapter:"第377章：巨金龙"},
        {key:"lt16",dataBase:"database4",chapter:"第六十二章 懵了！"},
        {key:"lt16",dataBase:"database4",chapter:"第六十六章 两个仇人"},
        {key:"lt16",dataBase:"database4",chapter:"第六十八章 一扇门"},
        {key:"lt16",dataBase:"database4",chapter:"第六十九章 因为他是我父亲"},
        {key:"lt16",dataBase:"database4",chapter:"第七十章 坚!"},
        {key:"lt16",dataBase:"database4",chapter:"第七十一章 忠王，长孙澜"},
        {key:"lt16",dataBase:"database4",chapter:"第七十三章 无际海角线"},
        {key:"lt16",dataBase:"database4",chapter:"第七十九章 抽门"},
        {key:"lt16",dataBase:"database4",chapter:"第九十章 找林小凡"},
        {key:"lt16",dataBase:"database4",chapter:"第九十三章 强子归来"},
        {key:"lt16",dataBase:"database4",chapter:"第一零五章 不成熟的地灵阵"},
        {key:"lt16",dataBase:"database4",chapter:"第一零九章 抵达上京！"},
        {key:"lt16",dataBase:"database4",chapter:"第一一零章 景帝，阴谋"},
        {key:"lt16",dataBase:"database4",chapter:"第一一四章 郦鞅"},
        {key:"lt16",dataBase:"database4",chapter:"第一一五章 一个都没死"},
        {key:"lt16",dataBase:"database4",chapter:"第一一六章 凡辰炼玄法门！"},
        {key:"lt16",dataBase:"database4",chapter:"第一一八章 天海浮空岛"},
        {key:"lt16",dataBase:"database4",chapter:"第④卷 玄女经"},
        {key:"lt16",dataBase:"database4",chapter:"第一二一章 得入城令"},
        {key:"lt16",dataBase:"database4",chapter:"第一二二章 天之城，古炼塔"},
        {key:"lt16",dataBase:"database4",chapter:"第一二三章 地阶能力融合"},
        {key:"lt16",dataBase:"database4",chapter:"第一二四章 樊京云的决定"},
        {key:"lt16",dataBase:"database4",chapter:"第一二五章 蓝顶楼"},
        {key:"lt16",dataBase:"database4",chapter:"第一二六章 进塔！"},
        {key:"lt16",dataBase:"database4",chapter:"第一二九章 血祭神坛"},
        {key:"lt16",dataBase:"database4",chapter:"第一三零章 禽系，剑道"},
        {key:"lt16",dataBase:"database4",chapter:"第一三二章 凹海，落荒岛"},
        {key:"lt16",dataBase:"database4",chapter:"第一三五章 骨骸"},
        {key:"lt16",dataBase:"database4",chapter:"第一三六章 信物，谜底"},
        {key:"lt16",dataBase:"database4",chapter:"第一三七章 破虚·万象千罗塔"},
        {key:"lt16",dataBase:"database4",chapter:"第一三八章 一波平，一波又起！"},
        {key:"lt16",dataBase:"database4",chapter:"第一三九章 程于旻，鲁嗔"},
        {key:"lt16",dataBase:"database4",chapter:"第一四零章 落荒岛之斗！"},
        {key:"lt16",dataBase:"database4",chapter:"第一四一章 冰炎韵音断魂掌"},
        {key:"lt16",dataBase:"database4",chapter:"第一四二章 断腿，一刀！"},
        {key:"lt16",dataBase:"database4",chapter:"第一四三章 困境"},
        {key:"lt16",dataBase:"database4",chapter:"第一四四章 内忧外患"},
        {key:"lt16",dataBase:"database4",chapter:"第一四五章 清清的心上人"},
        {key:"lt16",dataBase:"database4",chapter:"第一四八章 凤雏朽木阁"},
        {key:"lt16",dataBase:"database4",chapter:"第一四九章 寻踪石，断剑"},
        {key:"lt16",dataBase:"database4",chapter:"第一五零章 完全信任"},
        {key:"lt16",dataBase:"database4",chapter:"第一五一章 桑"},
        {key:"lt16",dataBase:"database4",chapter:"第一五五章 解密，禁典反噬"},
        {key:"lt16",dataBase:"database4",chapter:"第一五六章 反噬标准"},
        {key:"lt16",dataBase:"database4",chapter:"第一五七章 突破"},
        {key:"lt16",dataBase:"database4",chapter:"第一五八章 跳河"},
        {key:"lt16",dataBase:"database4",chapter:"第一六十五章 分道"},
        {key:"lt16",dataBase:"database4",chapter:"第一六八章 双蛟噬魂剑，出发！"},
        {key:"lt16",dataBase:"database4",chapter:"第一七零章 青州，小镇"},
        {key:"lt16",dataBase:"database4",chapter:"第一七一章 熟悉的身影"},
        {key:"lt16",dataBase:"database4",chapter:"第一七二章 三眼金狈"},
        {key:"lt16",dataBase:"database4",chapter:"第一七六章 狂狮鹫"},
        {key:"lt16",dataBase:"database4",chapter:"第一七七章 紫光骤降"},
        {key:"lt16",dataBase:"database4",chapter:"第一七八章 紫云鸢"},
        {key:"lt16",dataBase:"database4",chapter:"第一八四章 半秒，千米！"},
        {key:"lt16",dataBase:"database4",chapter:"第八十四章 宗级，变化！{召唤月票~"},
{key:"lt16",dataBase:"database4",chapter:"第五卷第九十八章 结果"},
{key:"lt16",dataBase:"database4",chapter:"第二二三章 启用三级破虚境"},
{key:"lt16",dataBase:"database4",chapter:"第七章 螺旋，爆气"},
{key:"lt16",dataBase:"database4",chapter:"第九章 第四次进化！"},
{key:"lt16",dataBase:"database4",chapter:"第十五章 安排"},
{key:"lt1719",dataBase:"database1",chapter:"第八十四章 洛水阁"},
{key:"lt1719",dataBase:"database1",chapter:"第八十七章  山门护法"},
{key:"lt1719",dataBase:"database1",chapter:"第八十八章  功法缺陷"},
{key:"lt1719",dataBase:"database1",chapter:"一百二十三章  魔道角力的开始【第二更】"},
{key:"lt1719",dataBase:"database1",chapter:"一百三十章 拔营北上"},
{key:"lt1719",dataBase:"database1",chapter:"一百四十一章 横扫将军岭（三）"},
{key:"lt1719",dataBase:"database1",chapter:"一百七十二章  浩吉伦达【第三更】"},
{key:"lt1719",dataBase:"database1",chapter:"一百八十章  玄意境的战斗"},
{key:"lt1719",dataBase:"database1",chapter:"一百九十七章 阴骨被擒【二合一】"},
{key:"lt1719",dataBase:"database1",chapter:"二百 一十七章 威压【第一更】"},
{key:"lt1719",dataBase:"database1",chapter:"二百一十六章  冰雪魔虎【二合一】"},
{key:"lt1719",dataBase:"database1",chapter:"二百二十章  玄妙境【第二更】"},
{key:"lt1719",dataBase:"database1",chapter:"二百三十二章  林海回归"},
{key:"lt1719",dataBase:"database1",chapter:"二百五十三章 九转杀阵（二）"},
{key:"lt1719",dataBase:"database1",chapter:"二百七十二章 请君入瓮"},
{key:"lt1719",dataBase:"database1",chapter:"二百七十八章  《生死决》"},
{key:"lt1719",dataBase:"database1",chapter:"三百二十九章  腊月初一"},
{key:"lt1719",dataBase:"database1",chapter:"三百五十八章  独自出行（下）"},
{key:"lt1719",dataBase:"database1",chapter:"三百八十八章  心悟法相生"},
{key:"lt1719",dataBase:"database1",chapter:"四百一十九章  会面"},
{key:"lt1719",dataBase:"database1",chapter:"五百零三章  激怒狼王"},
{key:"lt1719",dataBase:"database1",chapter:"五百六十七章  出境"},
{key:"lt1719",dataBase:"database1",chapter:"五百六十六章 敌退"},
{key:"lt1860",dataBase:"database1",chapter:"第225章：蛟王出战"},
{key:"lt1860",dataBase:"database1",chapter:"第286章：三年半（第三更，求订阅）"},
{key:"lt1863",dataBase:"database1",chapter:"第四百四十九章 惊天对撞"},
{key:"lt1863",dataBase:"database1",chapter:"第七百六十七章 鸿蒙"},
{key:"lt1864",dataBase:"database5",chapter:"第九十五章 争端 算账（二合一大章）"},
{key:"lt1904",dataBase:"database1",chapter:"第五卷神来之笔 第三十五章 明志"},
{key:"lt2004",dataBase:"database5",chapter:"三十九、莉莉姆.冯.因巴斯"},
{key:"lt2004",dataBase:"database5",chapter:"四十、法术对抗"},
{key:"lt2004",dataBase:"database5",chapter:"一百二十九、破坏成功"},
{key:"lt2004",dataBase:"database5",chapter:"二十九、挽歌"},
{key:"lt2004",dataBase:"database5",chapter:"一百二十六、精神能量构造体（下）"},
{key:"lt2058",dataBase:"database5",chapter:"第三百四十八章 西天冥辰 一顶帽子"},
{key:"lt22",dataBase:"database4",chapter:"第七十四章 暗 芒"},
{key:"lt22",dataBase:"database4",chapter:"第七十五章 巨大收获"},
{key:"lt22",dataBase:"database4",chapter:"第七十六章 隐宗来人"},
{key:"lt22",dataBase:"database4",chapter:"第一章 各方势动（一）"},
{key:"lt22",dataBase:"database4",chapter:"第一百一十一章  黑衣煞星「一更」"},
{key:"lt2263",dataBase:"database5",chapter:"第一百八十九章 演变本源法则"},
{key:"lt2325",dataBase:"database5",chapter:"第十六章 兽族号角"},
{key:"lt2325",dataBase:"database5",chapter:"第二十四章 启程"},
{key:"lt2325",dataBase:"database5",chapter:"第四章 考验"},
{key:"lt2325",dataBase:"database5",chapter:"第十五章 五只蜘蛛"},
{key:"lt2325",dataBase:"database5",chapter:"第二十二章 大战育母蜘蛛"},
{key:"lt2325",dataBase:"database5",chapter:"第七十八章 挽歌"},
{key:"lt2325",dataBase:"database5",chapter:"第四十四章 精神伤害"},
{key:"lt2325",dataBase:"database5",chapter:"第七十四章 意志永存"},
{key:"lt2325",dataBase:"database5",chapter:"第一百零三章 师徒"},
{key:"lt2325",dataBase:"database5",chapter:"第一百一十五章 战场"},
{key:"lt2325",dataBase:"database5",chapter:"第二十七章 风暴要塞"},
{key:"lt2395",dataBase:"database1",chapter:"第四十五章 辰弑"},
{key:"lt2338",dataBase:"database1",chapter:"第四百七十七章 神魂归一"},
{key:"lt2338",dataBase:"database1",chapter:"第四百七十六章 拔剑"},
{key:"lt2338",dataBase:"database1",chapter:"第四百七十五章 家庭和睦"},
{key:"lt2338",dataBase:"database1",chapter:"第四百七十九章 接近真像"},
{key:"lt2338",dataBase:"database1",chapter:"第四百七十三章 温情"},
{key:"lt2338",dataBase:"database1",chapter:"第四百七十四章 一怒红颜"},
{key:"lt2338",dataBase:"database1",chapter:"第四百八十六章 有如神助"},
{key:"lt2338",dataBase:"database1",chapter:"第四百八十章 逼迫现身"},
{key:"lt2338",dataBase:"database1",chapter:"第四百八十七章 回归故里"},
{key:"lt2338",dataBase:"database1",chapter:"第四百七十八章 大发神威"},
{key:"lt2338",dataBase:"database1",chapter:"第四百八十一章 天阙"},
{key:"lt2338",dataBase:"database1",chapter:"第四百八十五章 天泽"},
{key:"lt2338",dataBase:"database1",chapter:"第四百九十五章 合纵"},
{key:"lt2338",dataBase:"database1",chapter:"第四百九十二章 红粉骷髅"},
{key:"lt2338",dataBase:"database1",chapter:"第四百九十章 千里共婵娟"},
{key:"lt2338",dataBase:"database1",chapter:"第四百八十九章 忙碌"},
{key:"lt2338",dataBase:"database1",chapter:"第四百九十一章 惧内"},
{key:"lt2338",dataBase:"database1",chapter:"第四百九十三章 幽冥枯骨"},
{key:"lt2338",dataBase:"database1",chapter:"第四百八十八章一叶障目"},
{key:"lt2338",dataBase:"database1",chapter:"第四百九十四章 天降大任"},
{key:"lt25",dataBase:"database4",chapter:"第二十四章 你自杀吧"},
{key:"lt25",dataBase:"database4",chapter:"第二十五章 五十万碗神血"},
{key:"lt25",dataBase:"database4",chapter:"第二十六章 界主将臣"},
{key:"lt25",dataBase:"database4",chapter:"第二十七章 泰天地界"},
{key:"lt25",dataBase:"database4",chapter:"第二十八章 叫我‘上人’"},
{key:"lt25",dataBase:"database4",chapter:"第二十九章 大轮回幻阵"},
{key:"lt25",dataBase:"database4",chapter:"第三十三章 笛儿醒了"},
{key:"lt25",dataBase:"database4",chapter:"第三十四章 活了"},
{key:"lt25",dataBase:"database4",chapter:"第三十七章 始皇"},
{key:"lt25",dataBase:"database4",chapter:"第三十八章 猥琐的胖子"},
{key:"lt25",dataBase:"database4",chapter:"第三十九章 量天尺"},
{key:"lt25",dataBase:"database4",chapter:"第四十章 白虎分身"},
{key:"lt25",dataBase:"database4",chapter:"第四十一章 奥米罗"},
{key:"lt25",dataBase:"database4",chapter:"第四十八章 九曲恶阵"},
{key:"lt25",dataBase:"database4",chapter:"第六十五章 开创封阐教"},
{key:"lt25",dataBase:"database4",chapter:"第六十六章 舟十"},
{key:"lt25",dataBase:"database4",chapter:"第七十七章 混沌风暴"},
{key:"lt25",dataBase:"database4",chapter:"第七十八章 紫云"},
{key:"lt25",dataBase:"database4",chapter:"第二十一章 功德圆满"},
{key:"lt25",dataBase:"database4",chapter:"第二十二章 三魂七魄"},
{key:"lt25",dataBase:"database4",chapter:"第二十三章 开天辟的"},
{key:"lt25",dataBase:"database4",chapter:"第二十四章 如你所愿"},
{key:"lt25",dataBase:"database4",chapter:"第一百一十五章 连升三级"},
{key:"lt25",dataBase:"database4",chapter:"第四十一章 吾乃通天"},
{key:"lt25",dataBase:"database4",chapter:"第四十二章 苍穹现"},
{key:"lt25",dataBase:"database4",chapter:"第五十章 聚族成圣"},
{key:"lt25",dataBase:"database4",chapter:"第五十四章 强者聚集"},
{key:"lt25",dataBase:"database4",chapter:"第六十章 各有算计"},
{key:"lt25",dataBase:"database4",chapter:"第七十六章 德蒙之怒"},
{key:"lt25",dataBase:"database4",chapter:"第七十八章 强悍的第一大帝"},
{key:"lt25",dataBase:"database4",chapter:"第七十九章 四大混元会元始"},
{key:"lt2822",dataBase:"database1",chapter:"第二百零九章 痛苦的抉择"},
{key:"lt2822",dataBase:"database1",chapter:"第一百四十一章  生死"},
{key:"lt2892",dataBase:"database5",chapter:"第501章 【包子脸】"},
{key:"lt2892",dataBase:"database5",chapter:"第840章 【我妈年纪大了】"},
{key:"lt2892",dataBase:"database5",chapter:"第842章 【你会后悔的】"},
{key:"lt2892",dataBase:"database5",chapter:"第844章 【很有挑战性的妻子】"},
{key:"lt2892",dataBase:"database5",chapter:"第850章 【重口味】"},
{key:"lt2892",dataBase:"database5",chapter:"第849章 【打算追我】"},
{key:"lt2892",dataBase:"database5",chapter:"第848章 【真是活该】"},
{key:"lt2892",dataBase:"database5",chapter:"第843章 【完成你的愿望】"},
{key:"lt2892",dataBase:"database5",chapter:"第847章 【暂时别进去】"},
{key:"lt2892",dataBase:"database5",chapter:"第856章 【代表简】"},
{key:"lt2892",dataBase:"database5",chapter:"第1417章 【小爸爸】"},
{key:"lt2945",dataBase:"database1",chapter:"第一百四十四章吞天斩地"},
{key:"lt2945",dataBase:"database1",chapter:"第一百四十七章滴血群墓"},
{key:"lt2945",dataBase:"database1",chapter:"第一百四十八章从坟墓中走出来的小女孩"},
{key:"lt2945",dataBase:"database1",chapter:"第一百四十一章围杀巅峰圣人"},
{key:"lt2945",dataBase:"database1",chapter:"第一百五十章图穷匕见"},
{key:"lt2945",dataBase:"database1",chapter:"第一百五十一章斩杀绝世美人"},
{key:"lt2945",dataBase:"database1",chapter:"第一百五十四章妖帝留碑"},
{key:"lt2945",dataBase:"database1",chapter:"第一百六十七章怨龙索命"},
{key:"lt2945",dataBase:"database1",chapter:"第一百六十四章蛟龙化成龙山"},
{key:"lt2945",dataBase:"database1",chapter:"第一百六十一章嚣张跋扈"},
{key:"lt2945",dataBase:"database1",chapter:"第一百七十章胜者拥有郑玉儿"},
{key:"lt2945",dataBase:"database1",chapter:"第一百七十二章身具龙气"},
{key:"lt2945",dataBase:"database1",chapter:"第一百七十四章阴雷"},
{key:"lt2945",dataBase:"database1",chapter:"第一百八十四章一吼虚空裂"},
{key:"lt2945",dataBase:"database1",chapter:"第一百八十章三座灵石之山"},
{key:"lt2945",dataBase:"database1",chapter:"第一百八十七章血石破帝兵"},
{key:"lt2945",dataBase:"database1",chapter:"第一百八十六章公平一战的资格"},
{key:"lt2945",dataBase:"database1",chapter:"第一百八十九章坠落仙域"},
{key:"lt2945",dataBase:"database1",chapter:"第一百九十四章精神烙印"},
{key:"lt2945",dataBase:"database1",chapter:"第一百九十一章杀气破佛气"},
{key:"lt2945",dataBase:"database1",chapter:"第二百章金乌火树"},
{key:"lt2945",dataBase:"database1",chapter:"第一百九十七章三粒保命仙砂"},
{key:"lt2945",dataBase:"database1",chapter:"第二百一十四章隐形区域"},
{key:"lt2945",dataBase:"database1",chapter:"第二百一十六章选婿大会"},
{key:"lt2945",dataBase:"database1",chapter:"第二百一十章不死仙诀"},
{key:"lt2945",dataBase:"database1",chapter:"第二百二十章色宝两空"},
{key:"lt2945",dataBase:"database1",chapter:"第二百二十三章大帝后裔"},
{key:"lt2945",dataBase:"database1",chapter:"第二百二十六章赵宝对决季风翔"},
{key:"lt2945",dataBase:"database1",chapter:"第二百二十四章逆天生机"},
{key:"lt2945",dataBase:"database1",chapter:"第二百三十章九龙逆天"},
{key:"lt2945",dataBase:"database1",chapter:"第二百二十九章太阳帝决"},
{key:"lt2945",dataBase:"database1",chapter:"第二百三十六章镶着极品灵石的匕首更"},
{key:"lt2945",dataBase:"database1",chapter:"第二百三十四章惊艳一刀"},
{key:"lt2945",dataBase:"database1",chapter:"第二百五十章帝兵震凤仙城"},
{key:"lt2945",dataBase:"database1",chapter:"第二百四十九章形势比人强"},
{key:"lt2945",dataBase:"database1",chapter:"第二百五十三章认输的机会都没有"},
{key:"lt2945",dataBase:"database1",chapter:"第二百五十五章玩火自焚"},
{key:"lt2945",dataBase:"database1",chapter:"第二百六十一章宿命"},
{key:"lt2945",dataBase:"database1",chapter:"第二百六十二章灭绝人性"},
{key:"lt2945",dataBase:"database1",chapter:"第二百六十八章帝兵对峙"},
{key:"lt2945",dataBase:"database1",chapter:"第二百六十七章圣旨之力"},
{key:"lt2945",dataBase:"database1",chapter:"第二百六十九章仙砂回归人间"},
{key:"lt2945",dataBase:"database1",chapter:"第二百二十五章一念之间"},
{key:"lt2945",dataBase:"database1",chapter:"第二百七十章震慑群雄"},
{key:"lt2945",dataBase:"database1",chapter:"第二百六十六章山河玉玺"},
{key:"lt2945",dataBase:"database1",chapter:"第二百七十二章勾心斗角"},
{key:"lt2945",dataBase:"database1",chapter:"第二百八十一章冷血魔鬼"},
{key:"lt2945",dataBase:"database1",chapter:"第二百七十八章万变不离其宗"},
{key:"lt2945",dataBase:"database1",chapter:"第二百七十四章陷害"},
{key:"lt2945",dataBase:"database1",chapter:"第二百七十六章镇封巅峰神王"},
{key:"lt2945",dataBase:"database1",chapter:"第二百九十章麒麟妖兽族"},
{key:"lt2945",dataBase:"database1",chapter:"第二百九十一章望父成龙"},
{key:"lt2945",dataBase:"database1",chapter:"第二百九十四章镜中龙魂"},
{key:"lt2945",dataBase:"database1",chapter:"第二百九十七章太生猛了"},
{key:"lt2945",dataBase:"database1",chapter:"第六百三十四章血魔至尊"},
{key:"lt2945",dataBase:"database1",chapter:"第六百三十二章玄黄战甲"},
{key:"lt307",dataBase:"database4",chapter:"第二百五十章 亡灵的复仇"},
{key:"lt307",dataBase:"database4",chapter:"第二百五十九章 无从下手"},
{key:"lt307",dataBase:"database4",chapter:"第二百五十八章 没有选择"},
{key:"lt307",dataBase:"database4",chapter:"第二百五十一章 魔法师之战"},
{key:"lt307",dataBase:"database4",chapter:"第三百一十一章 四面开花"},
{key:"lt307",dataBase:"database4",chapter:"第三百一十二章 失误"},
{key:"lt307",dataBase:"database4",chapter:"第三百二十三章 邪恶魔灵"},
{key:"lt307",dataBase:"database4",chapter:"第三百四十三章 邪恶的邀请"},
{key:"lt307",dataBase:"database4",chapter:"第三百五十二章 危机前夕"},
{key:"lt307",dataBase:"database4",chapter:"第三百五十八章 找死的人"},
{key:"lt307",dataBase:"database4",chapter:"第三百七十五章 无形之军"},
{key:"lt3079",dataBase:"database1",chapter:"第4章 ：自求多福"},
{key:"lt3237",dataBase:"database5",chapter:"1108 血狼尊者的动之以情 第一更！"},
{key:"lt3237",dataBase:"database5",chapter:"1106 俺老孙是你家大圣爷爷！"},
{key:"lt3237",dataBase:"database5",chapter:"1122 承诺：三个月，结束战事！"},
{key:"lt3237",dataBase:"database5",chapter:"1126 两方动静"},
{key:"lt3277",dataBase:"database1",chapter:"第九章 平恶"},
{key:"lt3277",dataBase:"database1",chapter:"第二十四章 再遇周晴"},
{key:"lt3277",dataBase:"database1",chapter:"第十三章 警局激战(中)"},
    {key:"lt3277",dataBase:"database1",chapter:"第二十四章 龙泉酒厂"},
    {key:"lt3277",dataBase:"database1",chapter:"第二十三章 芽麦利用"},
    {key:"lt3277",dataBase:"database1",chapter:"第二十八章 李勇的家人"},
    {key:"lt3277",dataBase:"database1",chapter:"第二十六章 佳酿问世"},
    {key:"lt3277",dataBase:"database1",chapter:"第三十七章 辞职风波"},
    {key:"lt3277",dataBase:"database1",chapter:"第六十八章 网络大战"},
    {key:"lt3277",dataBase:"database1",chapter:"第七十五章 歇斯底里的李丽"},
    {key:"lt3277",dataBase:"database1",chapter:"第七十八章"},
    {key:"lt3277",dataBase:"database1",chapter:"第八十六章 回到家乡"},
    {key:"lt3277",dataBase:"database1",chapter:"第八十九章 张霞与三女"},
    {key:"lt3277",dataBase:"database1",chapter:"第一百零九章 材料学家秦海"},
    {key:"lt3458",dataBase:"database6",chapter:"第八百八十章 竞争激烈"},
    {key:"lt3476",dataBase:"database6",chapter:"第46章 ：混血美人"},
    {key:"lt496",dataBase:"database4",chapter:"第二集 米兰魔武学院 第二百二十五章 银龙公主的警告（下）"},
    {key:"lt513",dataBase:"database4",chapter:"第四百九十一章 终始（大结局中）"},
    {key:"lt513",dataBase:"database4",chapter:"第四百九十二章 终始（大结局下）"},
    {key:"lt513",dataBase:"database4",chapter:"第四百九十章 终始（大结局上）"},
    {key:"lt57",dataBase:"database4",chapter:"第三六四章 何去何从"},
    {key:"lt617",dataBase:"database4",chapter:"389章 战天使之觉醒"},
    {key:"lt617",dataBase:"database4",chapter:"391章 新的任务"},
    {key:"lt80",dataBase:"database4",chapter:"第三卷 第一百四十四章 十年约定"},
    {key:"lt80",dataBase:"database4",chapter:"第三卷 第一百六四章红颜祸水"},
    {key:"lt80",dataBase:"database4",chapter:"第三卷 第一百六十六章"},
    {key:"lt80",dataBase:"database4",chapter:"第三卷 第一百八十七章 王八之气"},
    {key:"lt80",dataBase:"database4",chapter:"第三卷 第一百八十八章 星杀"},
    {key:"lt80",dataBase:"database4",chapter:"第三卷 第一百九十八章龙组根据地"},
    {key:"lt872",dataBase:"database1",chapter:"第434章 孤身而出"},
    {key:"lt872",dataBase:"database1",chapter:"第699章 来自凡人界的警告！仙尊们的惊骇！"},
    {key:"lt872",dataBase:"database1",chapter:"第700章 布置四不象神阵"},
    {key:"lt872",dataBase:"database1",chapter:"第708章 潜入"},
    {key:"lt872",dataBase:"database1",chapter:"第712章"},
    {key:"lt872",dataBase:"database1",chapter:"第714章 正无聊 找你玩玩"},
    {key:"lt872",dataBase:"database1",chapter:"第717章 劫雷印"},
    {key:"lt872",dataBase:"database1",chapter:"第704章"},
    {key:"lt872",dataBase:"database1",chapter:"第705章 一氧化碳的“特攻”"},
    {key:"lt872",dataBase:"database1",chapter:"第702章"},
    {key:"lt872",dataBase:"database1",chapter:"第718章 超级中子星的战斗"},
    {key:"lt872",dataBase:"database1",chapter:"第711章 死邙寒漩"},
    {key:"lt872",dataBase:"database1",chapter:"第703章 彻底瓦解敌人的经济！"},
    {key:"lt872",dataBase:"database1",chapter:"第707章 超级神人在仙界!惊骇"},
    {key:"lt872",dataBase:"database1",chapter:"第739章 来者何人？"},
    {key:"lt872",dataBase:"database1",chapter:"第709章 危险越来越近"},
    {key:"lt872",dataBase:"database1",chapter:"第745章 危局"},
    {key:"lt872",dataBase:"database1",chapter:"第725章"},
    {key:"lt872",dataBase:"database1",chapter:"第722章 群战!铺天盖地的超级殭尸"},
    {key:"lt872",dataBase:"database1",chapter:"第744章 强收徒"},
    {key:"lt872",dataBase:"database1",chapter:"第741章 谁人能助？."},
    {key:"lt872",dataBase:"database1",chapter:"第749章"},
    {key:"lt872",dataBase:"database1",chapter:"第753章 弑师"},
    {key:"lt872",dataBase:"database1",chapter:"第755章 螳螂捕蝉"},
    {key:"lt872",dataBase:"database1",chapter:"第754章 斩除后患"},
    {key:"lt872",dataBase:"database1",chapter:"第751章 阴谋得逞！"},
    {key:"lt872",dataBase:"database1",chapter:"第771章 水无垢的危机!"},
    {key:"lt872",dataBase:"database1",chapter:"第773章 报复来临"},
    {key:"lt872",dataBase:"database1",chapter:"第759章 救援之人"},
    {key:"lt872",dataBase:"database1",chapter:"第772章 重伤! 三女蜕变"},
    {key:"lt872",dataBase:"database1",chapter:"第787章 寻找水无垢"},
    {key:"lt872",dataBase:"database1",chapter:"第801章 神王们的行动!"},
    {key:"lt872",dataBase:"database1",chapter:"第776章 一波三折"},
    {key:"lt872",dataBase:"database1",chapter:"第785章 强人来临"},
    {key:"lt872",dataBase:"database1",chapter:"第805章 布置惊天星系大阵"},
    {key:"lt872",dataBase:"database1",chapter:"第800章 第一神君的殒落！神界闹翻天！"},
    {key:"lt872",dataBase:"database1",chapter:"第823章 强者聚首 神王们的震骇"},
    {key:"lt872",dataBase:"database1",chapter:"第820章 抢劫神王？"},
    {key:"lt872",dataBase:"database1",chapter:"第811章 神界的第一人气偶像 神器之劫"},
    {key:"lt872",dataBase:"database1",chapter:"第798章 雪瑶投毒，巧中又巧，你中毒了"},
    {key:"lt872",dataBase:"database1",chapter:"第810章 神界记录的恐怖刷新者"},
    {key:"lt872",dataBase:"database1",chapter:"第824章 玄气宇宙成，至高神"},
    {key:"lt872",dataBase:"database1",chapter:"第822章 极点寸爆，化宇成宙！ 功德天兆"},
    {key:"lt872",dataBase:"database1",chapter:"第809章 神王也会阴沟翻船"},
    {key:"lt872",dataBase:"database1",chapter:"第814章 狂神光临! 水无垢的风采"},
    {key:"lt872",dataBase:"database1",chapter:"第815章 水无垢的修炼终点"},
    {key:"lt872",dataBase:"database1",chapter:"第842章 逆返能量石 水无垢遇险"},
    {key:"lt872",dataBase:"database1",chapter:"第843章 解除潜在危险! 生死路"},
    {key:"lt872",dataBase:"database1",chapter:"第846章 偷袭神王 被发现了么"},
    {key:"lt872",dataBase:"database1",chapter:"第845章 邪灵金光塔的主人 跟踪"},
    {key:"lt872",dataBase:"database1",chapter:"第847章 水无垢的恐惧"},
    {key:"lt872",dataBase:"database1",chapter:"第829章 玄金暗凤"},
    {key:"lt872",dataBase:"database1",chapter:"第853章 我就是我! 水无垢死了"},
    {key:"lt872",dataBase:"database1",chapter:"第859章 再与神王斗"},
    {key:"lt872",dataBase:"database1",chapter:"第858章 替神王清理门户"},
    {key:"lt872",dataBase:"database1",chapter:"第857章 为什么不能是我水无垢"},
    {key:"lt872",dataBase:"database1",chapter:"第863章 再回仙界。天庭悟情"},
    {key:"lt94",dataBase:"database4",chapter:"第68章 救人"},
    {key:"lt94",dataBase:"database4",chapter:"第67章 中箭"},
    {key:"lt94",dataBase:"database4",chapter:"第320章 闯关"},

];

    console.log(arry.length)
    arry = lodash.uniqWith(arry, lodash.isEqual)
    console.log(arry.length)

    arry.forEach(async function (item) {
        await saveData(item)
    })

};